version: '3.8'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: Backend-Bucharest-Airport
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./backend:/app
    environment:
      SPRING_PROFILES_ACTIVE: development
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/BucharestAirport
      SPRING_DATASOURCE_USERNAME: USERNAME
      SPRING_DATASOURCE_PASSWORD: PASSWORD
      FRONTEND_URL: http://localhost:3000
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: DB-Bucharest-Airport
    restart: always
    environment:
      POSTGRES_USER: USERNAME
      POSTGRES_PASSWORD: PASSWORD
      POSTGRES_DB: BucharestAirport
    ports:
      - "54320:5432"
    volumes:
      - db-data:/var/lib/postgresql/data

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: Frontend-Bucharest-Airport
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/src:/app/src
      - ./frontend/index.html:/app/index.html
    environment:
      REACT_APP_API_BASE_URL: http://localhost:8080
    command: ["npm", "run", "dev", "--", "--host"] # Expose to the network
    depends_on:
      - backend

volumes:
  db-data:
